function [Ki, info] = FullLoop_lookupKiFromSweep(scheduleCsv, brightnessLabel, loadRatio)
%FULLLOOP_LOOKUPKIFROMSWEEP Interpolate Ki from the DIAM4100 sweep schedule.
%
% Inputs:
%   scheduleCsv      DIAM4100_Ki_best_schedule.csv path
%   brightnessLabel  'B0'...'B5'
%   loadRatio        effective secondary VA / sweep nominal VA

    T = readtable(scheduleCsv, 'TextType', 'string');
    rows = T(T.Brightness == string(brightnessLabel), :);
    if isempty(rows)
        error('Brightness %s not found in Ki schedule %s.', brightnessLabel, scheduleCsv);
    end

    [x, order] = sort(rows.LoadRatio);
    y = rows.Ki(order);
    pass = rows.Pass(order);

    xClamped = min(max(loadRatio, min(x)), max(x));
    Ki = interp1(x, y, xClamped, 'linear');

    info = struct();
    info.brightness = char(brightnessLabel);
    info.requestedLoadRatio = loadRatio;
    info.clampedLoadRatio = xClamped;
    info.gridLoadRatios = x';
    info.gridKi = y';
    info.gridPass = pass';
    info.interpolation = 'linear';
    info.note = 'Ki interpolated from DIAM4100_Ki_best_schedule.csv generated by the sweep.';
end
