function results = DIAM4100_validateControl(varargin)
%DIAM4100_VALIDATECONTROL Sweep brightness and effective load for CCR validation.
%
% This script validates the current model against the numerical limits used
% for design:
%   - FAA AC 150/5345-10H: selected current within +/-0.1 A and stabilized
%     within 5 s for 6.6 A CCRs; no >120% transient longer than 250 ms.
%   - IEC 61822 / IEC 61820-3-2 continuity: 6.7 Arms surge ceiling for
%     brightness switching and 500 ms target after dynamic disturbance.
%
% Example:
%   results = DIAM4100_validateControl('SaveModel', false);

    opts = localParseInputs(varargin{:});
    thisDir = fileparts(mfilename('fullpath'));
    addpath(thisDir);

    run(fullfile(thisDir, 'DIAM4100_simParams.m'));
    baseParams = evalin('base', 'DIAM4100');

    model = baseParams.model.name;
    rows = {};

    for loadRatio = opts.LoadRatios
        for b = opts.BrightnessIndices
            DIAM4100_user = struct();
            DIAM4100_user.loadTap.eighths = baseParams.loadTap.eighths;
            DIAM4100_user.load.effectivePower_VA = ...
                baseParams.load.ledNominalPower_VA * loadRatio;
            DIAM4100_user.control.activeBrightness = b;
            assignin('base', 'DIAM4100_user', DIAM4100_user);

            run(fullfile(thisDir, 'DIAM4100_simParams.m'));
            DIAM4100_applyModelParameters('SaveModel', opts.SaveModel, 'Instrument', true);
            DIAM4100 = evalin('base', 'DIAM4100');

            try
                simOut = sim(model, ...
                    'StopTime', num2str(DIAM4100.validation.simTime_s), ...
                    'ReturnWorkspaceOutputs', 'on');
                Irms = simOut.get('DIAM4100_Irms');
                metrics = DIAM4100_measureResponse(Irms.Time, ...
                                                   squeeze(Irms.Data), ...
                                                   DIAM4100.control.Iref_Arms, ...
                                                   DIAM4100.norms);
                err = "";
            catch ME
                metrics = localEmptyMetrics(DIAM4100.control.Iref_Arms);
                err = string(ME.message);
            end

            rows(end+1, :) = { ...
                DIAM4100.loadTap.eighths, ...
                DIAM4100.load.nominalRatio, ...
                DIAM4100.load.effectivePower_VA, ...
                DIAM4100.load.R_ohm, ...
                string(DIAM4100.control.activeBrightnessLabel), ...
                DIAM4100.control.Iref_Arms, ...
                DIAM4100.control.Ki, ...
                metrics.peak_Arms, ...
                metrics.overshoot_A, ...
                metrics.overshoot_pct, ...
                metrics.final_Arms, ...
                metrics.finalError_A, ...
                metrics.settlingTime_s, ...
                metrics.maxContinuous120Duration_s, ...
                metrics.meetsFAASettling, ...
                metrics.meetsIECSettling, ...
                ~metrics.exceedsFAA120Duration, ...
                ~metrics.exceedsIECStepLimit, ...
                metrics.pass, ...
                err};
        end
    end

    results = cell2table(rows, 'VariableNames', { ...
        'LoadTap_eighths', ...
        'LoadRatio', ...
        'LoadPower_VA', ...
        'LoadResistance_ohm', ...
        'Brightness', ...
        'Iref_Arms', ...
        'Ki', ...
        'Peak_Arms', ...
        'Overshoot_A', ...
        'Overshoot_pct', ...
        'Final_Arms', ...
        'FinalError_A', ...
        'SettlingTime_s', ...
        'MaxContinuous120Duration_s', ...
        'MeetsFAASettling', ...
        'MeetsIECSettling', ...
        'MeetsFAATransient120Duration', ...
        'MeetsIECStepSurgeLimit', ...
        'Pass', ...
        'Error'});

    try
        writetable(results, baseParams.validation.outputCsv);
    catch ME
        warning('DIAM4100:ValidationCsvSkipped', ...
            'Could not write validation CSV: %s', ME.message);
    end

    assignin('base', 'DIAM4100_validation_results', results);
    evalin('base', 'clear DIAM4100_user');
end

function opts = localParseInputs(varargin)
    parser = inputParser;
    parser.addParameter('BrightnessIndices', 1:6, @(x) isnumeric(x) && all(x >= 1));
    parser.addParameter('LoadRatios', [0.20 0.35 0.50 0.75 1.00], ...
        @(x) isnumeric(x) && all(x > 0));
    parser.addParameter('SaveModel', false, @(x) islogical(x) || isnumeric(x));
    parser.parse(varargin{:});
    opts = parser.Results;
end

function metrics = localEmptyMetrics(ref_Arms)
    metrics = struct();
    metrics.reference_Arms = ref_Arms;
    metrics.peak_Arms = NaN;
    metrics.final_Arms = NaN;
    metrics.finalError_A = NaN;
    metrics.overshoot_A = NaN;
    metrics.overshoot_pct = NaN;
    metrics.settlingTime_s = NaN;
    metrics.maxContinuous120Duration_s = NaN;
    metrics.exceedsIECStepLimit = true;
    metrics.exceedsFAA120Duration = true;
    metrics.meetsFAASettling = false;
    metrics.meetsIECSettling = false;
    metrics.pass = false;
end
