function DIAM4100_applyModelParameters(varargin)
%DIAM4100_APPLYMODELPARAMETERS Replace hard-coded Simulink values by workspace parameters.
%
% Usage:
%   run DIAM4100_simParams
%   DIAM4100_applyModelParameters('SaveModel', true)
%
% This function is intentionally idempotent: running it several times keeps
% the same model structure and simply refreshes parameters.

    opts = localParseInputs(varargin{:});
    thisDir = fileparts(mfilename('fullpath'));
    addpath(thisDir);

    if evalin('base', 'exist(''DIAM4100'', ''var'')') ~= 1
        run(fullfile(thisDir, 'DIAM4100_simParams.m'));
    end
    DIAM4100 = evalin('base', 'DIAM4100');

    model = DIAM4100.model.name;
    modelFile = fullfile(thisDir, [model '.slx']);
    load_system(modelFile);

    localSet([model '/AC Voltage Source'], ...
        'Amplitude', 'DIAM4100.grid.Vpk', ...
        'Frequency', 'DIAM4100.grid.f_Hz');

    localSet([model '/Constant'], ...
        'Value', 'DIAM4100.control.Iref_Arms');

    localSet([model '/Constant1'], ...
        'Value', 'DIAM4100.control.alphaMin_deg');

    localSet([model '/Constant2'], ...
        'Value', 'DIAM4100.control.alphaOffset_deg');

    localSet([model '/Discrete PID Controller'], ...
        'P', 'DIAM4100.control.Kp', ...
        'I', 'DIAM4100.control.Ki', ...
        'SampleTime', 'DIAM4100.control.Ts_s', ...
        'UpperSaturationLimit', 'DIAM4100.control.alphaMax_deg', ...
        'LowerSaturationLimit', 'DIAM4100.control.alphaMin_deg', ...
        'InitialConditionForIntegrator', 'DIAM4100.control.integratorIC_deg');

    localSet([model '/Linear Transformer'], ...
        'NominalPower', 'DIAM4100.transformer.NominalPower', ...
        'winding1', 'DIAM4100.transformer.winding1', ...
        'winding2', 'DIAM4100.transformer.winding2', ...
        'RmLm', 'DIAM4100.transformer.RmLm');

    localSet([model '/Series RLC Branch'], ...
        'Resistance', 'DIAM4100.load.R_ohm', ...
        'Inductance', 'DIAM4100.load.L_H', ...
        'Capacitance', 'DIAM4100.load.C_F');

    localSet([model '/RMS'], ...
        'Freq', 'DIAM4100.grid.f_Hz');

    localSet([model '/PLL'], ...
        'Fmin', '45', ...
        'Par_Init', '[0 DIAM4100.grid.f_Hz]', ...
        'TcD', 'DIAM4100.control.Ts_s');

    localSet([model '/Thyristor'], ...
        'Ron', 'DIAM4100.thyristor.Ron_ohm', ...
        'Lon', 'DIAM4100.thyristor.Lon_H', ...
        'Vf', 'DIAM4100.thyristor.Vf_V', ...
        'Rs', 'DIAM4100.thyristor.Rs_ohm', ...
        'Cs', 'DIAM4100.thyristor.Cs_F');

    localSet([model '/Thyristor1'], ...
        'Ron', 'DIAM4100.thyristor.Ron_ohm', ...
        'Lon', 'DIAM4100.thyristor.Lon_H', ...
        'Vf', 'DIAM4100.thyristor.Vf_V', ...
        'Rs', 'DIAM4100.thyristor.Rs_ohm', ...
        'Cs', 'DIAM4100.thyristor.Cs_F');

    pulseBlock = sprintf('%s/Pulse Generator\n(Thyristor, 6-Pulse)', model);
    localSet(pulseBlock, ...
        'pwidth', 'DIAM4100.pulse.pwidth_deg', ...
        'Ts', 'DIAM4100.control.Ts_s');

    localSet([model '/powergui'], ...
        'SampleTime', 'DIAM4100.powergui.Ts_s', ...
        'frequency', 'DIAM4100.grid.f_Hz', ...
        'frequencyindice', 'DIAM4100.grid.f_Hz', ...
        'fundamental', 'DIAM4100.grid.f_Hz');

    set_param(model, ...
        'StopTime', 'DIAM4100.validation.simTime_s', ...
        'SignalLogging', 'on', ...
        'ReturnWorkspaceOutputs', 'on');

    if opts.Instrument
        localEnsureToWorkspace(model, 'RMS', 'DIAM4100_Irms_ToWorkspace', 'DIAM4100_Irms');
    end

    if opts.SaveModel
        save_system(model);
    end

    fprintf('DIAM4100 parameters applied to %s. SaveModel=%d\n', model, opts.SaveModel);
end

function opts = localParseInputs(varargin)
    parser = inputParser;
    parser.addParameter('SaveModel', false, @(x) islogical(x) || isnumeric(x));
    parser.addParameter('Instrument', true, @(x) islogical(x) || isnumeric(x));
    parser.parse(varargin{:});
    opts = parser.Results;
end

function localSet(blockPath, varargin)
    try
        set_param(blockPath, varargin{:});
    catch ME
        warning('DIAM4100:ApplySkipped', ...
            'Could not set parameters on "%s": %s', blockPath, ME.message);
    end
end

function localEnsureToWorkspace(model, sourceBlockName, sinkBlockName, variableName)
    sinkPath = [model '/' sinkBlockName];
    if isempty(find_system(model, 'SearchDepth', 1, 'Name', sinkBlockName))
        add_block('simulink/Sinks/To Workspace', sinkPath, ...
            'VariableName', variableName, ...
            'SaveFormat', 'Timeseries', ...
            'MaxDataPoints', 'inf', ...
            'Position', [1210 170 1280 200]);
    else
        set_param(sinkPath, ...
            'VariableName', variableName, ...
            'SaveFormat', 'Timeseries', ...
            'MaxDataPoints', 'inf');
    end

    try
        add_line(model, [sourceBlockName '/1'], [sinkBlockName '/1'], 'autorouting', 'on');
    catch ME
        if ~contains(ME.message, 'already')
            warning('DIAM4100:InstrumentationSkipped', ...
                'Could not connect %s to %s: %s', sourceBlockName, sinkBlockName, ME.message);
        end
    end
end
